language: php 

php:
  - 7.0

notifications:
  email: false
  irc: "irc.efnet.org#php.yaf"


   
env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

#Compile
before_script:
    - ./travis/compile.sh

# Run PHPs run-tests.php 
script: TEST_PHP_ARGS="--show-diff" make test
